import React from 'react'
import CourseLandingPage from '../../components/CourseLandingPage'
import type { CourseLandingData } from '../../components/CourseLandingPage'

const data: CourseLandingData = {
  slug:'ai-prompt-engineering', title:'AI & Prompt Engineering', badge:'✨',
  tagline:'44 lessons — the deepest AI prompt engineering course in Africa.',
  description:'The most comprehensive AI & prompt engineering course on the platform. From fundamentals to building AI-powered Python applications with advanced prompting techniques.',
  level:'advanced', category:'AI & Prompting', price_ngn:50000, xp_total:440, cert_level:'executive',
  modules:[
    {step:1, title:'AI & LLM Fundamentals',         description:'How large language models work.',                                type:'concept'},
    {step:2, title:'What is Prompt Engineering',    description:'The science and art of prompting AI systems.',                  type:'concept'},
    {step:3, title:'Zero-shot Prompting',            description:'Getting accurate results without examples.',                    type:'concept'},
    {step:4, title:'One-shot Prompting',             description:'Guiding AI with a single example.',                            type:'concept'},
    {step:5, title:'Few-shot Prompting',             description:'Using multiple examples to guide AI output.',                  type:'concept'},
    {step:6, title:'Prompt Exercise I',              description:'Write effective prompts for real Python tasks.',                type:'exercise'},
    {step:7, title:'Chain-of-thought Prompting',     description:'Step-by-step reasoning prompts.',                             type:'concept'},
    {step:8, title:'Self-consistency',               description:'Sampling multiple paths and choosing the best answer.',        type:'concept'},
    {step:9, title:'Tree of Thoughts',               description:'Exploring multiple reasoning branches.',                       type:'concept'},
    {step:10,title:'Role Prompting',                 description:'Assigning expert personas to guide model behaviour.',          type:'concept'},
    {step:11,title:'Instruction Prompting',          description:'Writing precise, unambiguous instructions.',                   type:'concept'},
    {step:12,title:'Prompt Exercise II',             description:'Advanced prompt patterns in practice.',                        type:'exercise'},
    {step:13,title:'Prompt Templates',               description:'Building reusable, parameterised prompt structures.',          type:'concept'},
    {step:14,title:'Prompt Chaining',                description:'Linking prompts to build complex multi-step workflows.',       type:'concept'},
    {step:15,title:'Output Formatting',              description:'Getting structured JSON, Markdown, and code outputs.',         type:'concept'},
    {step:16,title:'Context Management',             description:'Managing conversation history and context windows.',           type:'concept'},
    {step:17,title:'Retrieval-Augmented Generation', description:'Combining prompting with external knowledge sources.',         type:'concept'},
    {step:18,title:'RAG Exercise',                   description:'Build a simple RAG pipeline in Python.',                       type:'exercise'},
    {step:19,title:'Function Calling',               description:'Letting AI call Python functions and tools.',                  type:'concept'},
    {step:20,title:'Function Calling Exercise',      description:'Implement function calling with the Groq/OpenAI API.',         type:'exercise'},
    {step:21,title:'Agents & Autonomy',              description:'Building AI agents that plan and execute tasks.',              type:'concept'},
    {step:22,title:'Agent Exercise',                 description:'Build a simple Python agent with tool use.',                   type:'exercise'},
    {step:23,title:'Groq API Integration',           description:'Call LLMs from Python using the Groq API.',                   type:'concept'},
    {step:24,title:'OpenAI API Integration',         description:'Using the OpenAI Python SDK for completions and embeddings.',  type:'concept'},
    {step:25,title:'Embeddings & Semantic Search',   description:'Creating and searching vector embeddings.',                    type:'concept'},
    {step:26,title:'Embeddings Exercise',            description:'Build a semantic search engine in Python.',                    type:'exercise'},
    {step:27,title:'Fine-tuning Basics',             description:'When and how to fine-tune a language model.',                  type:'concept'},
    {step:28,title:'Safety & Responsible AI',        description:'Bias, hallucination, jailbreaks, and ethical prompting.',     type:'concept'},
    {step:29,title:'Prompt Injection & Defence',     description:'Security risks in prompt-driven applications.',                type:'concept'},
    {step:30,title:'AI Safety Exercise',             description:'Identify and mitigate prompt injection vulnerabilities.',      type:'exercise'},
    {step:31,title:'Building an AI Chatbot',         description:'End-to-end Python chatbot with LLM backbone.',                type:'codegen'},
    {step:32,title:'Building a Code Assistant',      description:'AI-powered code review and generation tool.',                  type:'codegen'},
    {step:33,title:'Building a Data Analyst Agent',  description:'AI agent that analyses CSV data and generates reports.',       type:'codegen'},
    {step:34,title:'Building a Content Generator',   description:'Automated blog post and marketing copy generator.',           type:'codegen'},
    {step:35,title:'LangChain Fundamentals',         description:'Using LangChain to build AI applications.',                   type:'concept'},
    {step:36,title:'LangChain Exercise',             description:'Build a LangChain chain with memory.',                        type:'exercise'},
    {step:37,title:'Vector Databases',               description:'Pinecone, Chroma, and FAISS for AI memory.',                  type:'concept'},
    {step:38,title:'Multi-modal Prompting',          description:'Prompting with images, audio, and documents.',                type:'concept'},
    {step:39,title:'Production AI Systems',          description:'Deploying AI applications to production.',                    type:'concept'},
    {step:40,title:'Monitoring & Observability',     description:'Tracking LLM usage, costs, and quality.',                     type:'concept'},
    {step:41,title:'AI Engineering Best Practices',  description:'Patterns for reliable, scalable AI applications.',            type:'concept'},
    {step:42,title:'AI & Prompt Engineering Quiz',   description:'Comprehensive test of your AI knowledge.',                    type:'quiz'},
    {step:43,title:'Capstone Project I',             description:'Build an AI-powered Python tutor chatbot.',                   type:'codegen'},
    {step:44,title:'Capstone Project II',            description:'Build a full AI agent with tools, memory, and deployment.',   type:'codegen'},
  ],
}
export default function AiPromptEngineeringPage() { return <CourseLandingPage data={data} /> }
